name: Continuous Integration

# Event triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Environment
env:
  BUILD_TYPE: Release

# Jobs
jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Print info
      - name: How Many Cores Do We Have?
        run: nproc --all

      # Build and install using CMake
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/build/boost-prefix
            ${{ github.worksapce }}/build/opencv-prefix
          key: dependencies
      - name: Configure
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel $(nproc --all)
      - name: Install
        run: sudo cmake --install ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python Dependencies
        run: pip install -r python/requirements.txt

      # Run Test
      - name: Run Integration Tests
        run: python3 ./run.py
        working-directory: python/integration_test
