name: Continuous Integration

# Event triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Environment
env:
  BUILD_TYPE: Release
  ROOT_DIR: ${{ github.workspace }}

# Jobs
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: sh
            installer: sh
            sudo: sudo
          - os: macos-latest
            script: sh
            installer: sh
            sudo: sudo
          - os: windows-latest
            script: ps1
            installer: exe
            sudo: ''
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Build dependencies
      - name: Build Dependencies
        run: ${{ github.workspace }}/env/build-deps.${{ matrix.script }}

      # Build package using CMake and cpack
      - name: Configure
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DCPACK_PACKAGE_FILE_NAME=FracTool-${{ github.ref_name }}-${{ runner.os }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel $(nproc --all)
      - name: Run CPack
        run: ${{ matrix.sudo }} cpack
        working-directory: ${{ github.workspace }}/build

      # Upload installer artifact
      - name: Publish installer
        uses: actions/upload-artifact@v3
        with:
          name: FracTool-${{ github.ref_name }}-${{ runner.os }}
          path: ${{ github.workspace }}/build/FracTool-${{ github.ref_name }}-${{ runner.os }}.${{ matrix.installer }}

  integration:
    name: Integration Test
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: sh
            installer: sh
            installer_switch: --skip-license --prefix
            installer_prefix: /usr/local
            sudo: sudo
          - os: macos-latest
            script: sh
            installer: sh
            installer_switch: --skip-license --prefix
            installer_prefix: /usr/local
            sudo: sudo
          - os: windows-latest
            script: ps1
            installer: exe
            installer_switch: /D
            installer_prefix: "C:\\Program Files\\FracTool"
            sudo: ''
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Download appropriate artifact
      - name: Download Installer
        uses: actions/download-artifact@v3
        with:
          name: FracTool-${{ github.ref_name }}-${{ runner.os }}
      - name: Change Permissions (Linux/MacOS)
        if: ${{ runner.os != 'Windows' }}
        run: chmod a+x FracTool-${{ github.ref_name }}-${{ runner.os }}.${{ matrix.installer }}

      # Run installer
      - name: Install
        run: |
          ${{ matrix.sudo }} ./FracTool-${{ github.ref_name }}-${{ runner.os }}.${{ matrix.installer }} ${{ matrix.installer_switch }}=${{ matrix.installer_prefix }}
          echo ${{ matrix.installer_prefix }}/bin >> $GITHUB_PATH

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python Dependencies
        run: pip install -r python/requirements.txt

      # Run Test
      - name: Run Integration Tests
        run: python3 ./run.py
        working-directory: python/integration_test