name: Continuous Integration

# Event triggers
on:
  push:
  pull_request:
    branches:
      - main

# Environment
env:
  BUILD_TYPE: Release

# Jobs
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Install Dependencies
      - name: Build Boost
        id: boost
        uses: egor-tensin/build-boost@v1
        with:
          version: 1.73.0
          libraries: log program_options
          configuration: ${{env.BUILD_TYPE}}
      - name: Cache OpenCV
        id: opencv-cache
        uses: actions/cache@v2
        with:
          path: ./opencv-install
          key: ${{ runner.os }}-opencv-cache
      - name: Install OpenCV
        uses: rayandrews/with-opencv-action@v1
        with:  
          dir: ./opencv-install
          cached: ${{ steps.opencv-cache.outputs.cache-hit }}
          opencv-version: '4.5.0'

      # Build using CMake
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.root }}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # Deploy build artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fractool-cli
          path: build/out/fractool/fractool

  integration:
    name: Integration Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # Checkout Code and setup Python
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install Dependencies
      - name: Build Boost
        id: boost
        uses: egor-tensin/build-boost@v1
        with:
            version: 1.73.0
            libraries: log program_options
            configuration: ${{env.BUILD_TYPE}}
      - name: Cache OpenCV
        id: opencv-cache
        uses: actions/cache@v2
        with:
          path: ./opencv-install
          key: ${{ runner.os }}-opencv-cache
      - name: Install OpenCV
        uses: rayandrews/with-opencv-action@v1
        with:  
          dir: ./opencv-install
          cached: ${{ steps.opencv-cache.outputs.cache-hit }}
          opencv-version: '4.5.0'
      - name: Install Python Dependencies
        run: pip install -r scripts/integration_test/requirements.txt

      # Download Artifact
      - name: Download Fractool CLI
        uses: actions/download-artifact@v2
        with:
          name: fractool-cli
          path: build/out/fractool/
      - name: Update Artifact Permissions
        run: chmod a+x build/out/fractool/fractool

      # Run Test
      - name: Run Integration Tests
        run: python3 ./run.py
        working-directory: scripts/integration_test
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}